version: '3.8'

services:
  api:
    build: .
    ports:
      - "8000:8000"
    env_file:
      - .env
    volumes:
      - ./docs:/app-container/docs
      - ./faiss_index:/app-container/faiss_index
